### ISSUE TITLE
Selected present mode Mailbox is not supported by the used Vulkan physical device.

### ISSUE THREAD

**Issue by SteveEbey73742** [vkmark/vkmark#14]
Fedora 27, Nvidia proprietary 390.25 on GTX 970 with 4Gig ram, amd fx6350 six core processor, 16gb ram, screen resolution 1680x1050
cli used is vkmark --fullscreen
Xorg server, Cinnamon Desktop. all relevant vulkan library files installed, vulkan caps runs and shows the card is detected.  Is it a limitation with vulkan doing fullscreen in linux?

```
Debug: WindowSystemLoader: Looking in /usr/lib64/vkmark for window system plugins
Debug: WindowSystemLoader: Loading options from /usr/lib64/vkmark/kms.so... ok
Debug: WindowSystemLoader: Loading options from /usr/lib64/vkmark/wayland.so... ok
Debug: WindowSystemLoader: Loading options from /usr/lib64/vkmark/xcb.so... ok
Debug: WindowSystemLoader: Probing /usr/lib64/vkmark/kms.so... succeeded with priority 0
Debug: WindowSystemLoader: Probing /usr/lib64/vkmark/wayland.so... succeeded with priority 0
Debug: WindowSystemLoader: Probing /usr/lib64/vkmark/xcb.so... succeeded with priority 127
Debug: WindowSystemLoader: Selected window system plugin /usr/lib64/vkmark/xcb.so (best match)
Debug: XcbNativeSystem: Using root visual 0x21 for window
Debug: VulkanState: Using queue family index 0 for WSI operations
Debug: VulkanState: Using queue family index 0 for rendering
Debug: SwapchainWindowSystem: Available surface format B8G8R8A8Unorm
Debug: SwapchainWindowSystem: Available surface format B8G8R8A8Srgb
Debug: SwapchainWindowSystem: Selected swapchain format B8G8R8A8Srgb
Error: Selected present mode Mailbox is not supported by the used Vulkan physical device.


```

**Comment by afrantzis** [comment]
My guess is that is a limitation of the drivers in the fullscreen mode. "mailbox" is the preferred present mode for benchmarking, but if the driver doesn't support it you can select another mode with the -p,--present-mode command line option (see vkmark -h). Note that depending on the present mode you may get different benchmarking results (e.g. some modes are synced to vsync so you will get an 60 FPS cap).

Does running non-fullscreen work without explicitly setting a --present-mode?

**Comment by SteveEbey73742** [comment]
=======================================================
    vkmark 2017.08
=======================================================
    Vendor ID:      0x10DE
    Device ID:      0x13C2
    Device Name:    GeForce GTX 970
    Driver Version: 1636188160
=======================================================
[vertex] device-local=true: FPS: 4214 FrameTime: 0.237 ms
[vertex] device-local=false: FPS: 3690 FrameTime: 0.271 ms
[texture] anisotropy=0: FPS: 4192 FrameTime: 0.239 ms
[texture] anisotropy=16: FPS: 4186 FrameTime: 0.239 ms
[shading] shading=gouraud: FPS: 3915 FrameTime: 0.255 ms
[shading] shading=blinn-phong-inf: FPS: 3921 FrameTime: 0.255 ms
[shading] shading=phong: FPS: 3895 FrameTime: 0.257 ms
[shading] shading=cel: FPS: 3926 FrameTime: 0.255 ms
[effect2d] kernel=edge: FPS: 4078 FrameTime: 0.245 ms
[effect2d] kernel=blur: FPS: 2628 FrameTime: 0.381 ms
[desktop] <default>: FPS: 4072 FrameTime: 0.246 ms
[cube] <default>: FPS: 5388 FrameTime: 0.186 ms
[clear] <default>: FPS: 5503 FrameTime: 0.182 ms
=======================================================
                                   vkmark Score: 4123
=======================================================

command used - vkmark --fullscreen -p immediate

**Comment by leigh123linux** [comment]
Nvidia never supported mailbox

```
$ vulkaninfo |grep -a4 -i 'Present Modes'
Surface type : VK_KHR_xcb_surface
Formats:		count = 2
	B8G8R8A8_UNORM
	B8G8R8A8_SRGB
Present Modes:		count = 3
	FIFO_KHR
	FIFO_RELAXED_KHR
	IMMEDIATE_KHR

```

**Comment by 82157402** [comment]
![image](https://user-images.githubusercontent.com/12945580/221138694-4fe1db21-93ad-4141-a300-aa7bd5438b8d.png)
It show "Error: Selected present mode Mailbox is not supported by the used Vulkan physical device" when vkmark is running
How to run vkMark?

**Comment by Franck-Nein** [comment]
@82157402 
Try 
```
./build/src/vkmark --winsys-dir=build/src --data-dir=data -p immediate
```
