### ISSUE TITLE
Missing a line of code @ src/ws/wayland_native_system.cpp

### ISSUE THREAD

**Issue by Michaelypk** [vkmark/vkmark#32]
This causes the compositor to get no Pong feedback. I tested it on kwin_wayland and found that the window turned gray.

diff --git a/src/ws/wayland_native_system.cpp b/src/ws/wayland_native_system.cpp
index c2dd00c..52eb9e6 100644
--- a/src/ws/wayland_native_system.cpp
+++ b/src/ws/wayland_native_system.cpp
@@ -314,6 +314,8 @@ void WaylandNativeSystem::handle_registry_global(
                 registry, id, &xdg_wm_base_interface, std::min(version, 2U)));
         wws->xdg_wm_base = ManagedResource<struct xdg_wm_base*>{
             std::move(xdg_wm_base_raw), xdg_wm_base_destroy};
+
+        xdg_wm_base_add_listener(wws->xdg_wm_base, &xdg_wm_base_listener, wws);
     }
     else if (interface == "wl_seat")
     {

**Comment by afrantzis** [comment]
Thanks!
